### ISSUE TITLE
1.19.4 Support

### ISSUE THREAD

**Issue by SamB440** [Shynixn/StructureBlockLib#109]
Since updating to 1.19.4, SBL no longer works:
```
[19:17:25 WARN]: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
[19:17:25 WARN]:        at com.github.shynixn.structureblocklib.api.bukkit.StructureBlockLib.loadStructure(StructureBlockLib.java:84)
[19:17:25 WARN]:        at Battlegrounds-1.0.0-SNAPSHOT.jar//org.empirewar.battlegrounds.game.siege.placeable.Placeable.load(Placeable.java:168)
[19:17:25 WARN]:        at Battlegrounds-1.0.0-SNAPSHOT.jar//org.empirewar.battlegrounds.game.siege.placeable.Placeable.load(Placeable.java:156)
[19:17:25 WARN]:        at Battlegrounds-1.0.0-SNAPSHOT.jar//org.empirewar.battlegrounds.game.siege.placeable.Placeable.cache(Placeable.java:82)
[19:17:25 WARN]:        at Battlegrounds-1.0.0-SNAPSHOT.jar//org.empirewar.battlegrounds.game.siege.placeable.Placeable.<init>(Placeable.java:75)
[19:17:25 WARN]:        at Battlegrounds-1.0.0-SNAPSHOT.jar//org.empirewar.battlegrounds.game.siege.placeable.Placeable.lambda$static$1(Placeable.java:50)
[19:17:25 WARN]:        at com.mojang.serialization.DataResult$Instance.ap3(DataResult.java:340)
[19:17:25 WARN]:        at com.mojang.serialization.codecs.RecordCodecBuilder$Instance$5.decode(RecordCodecBuilder.java:321)
[19:17:25 WARN]:        at com.mojang.serialization.codecs.RecordCodecBuilder$2.decode(RecordCodecBuilder.java:107)
[19:17:25 WARN]:        at com.mojang.serialization.MapDecoder.lambda$compressedDecode$1(MapDecoder.java:52)
[19:17:25 WARN]:        at com.mojang.serialization.DataResult.lambda$flatMap$11(DataResult.java:139)
[19:17:25 WARN]:        at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
[19:17:25 WARN]:        at com.mojang.serialization.DataResult.flatMap(DataResult.java:137)
[19:17:25 WARN]:        at com.mojang.serialization.MapDecoder.compressedDecode(MapDecoder.java:52)
[19:17:25 WARN]:        at com.mojang.serialization.MapCodec$MapCodecCodec.decode(MapCodec.java:91)
[19:17:25 WARN]:        at com.mojang.serialization.codecs.ListCodec.lambda$decode$2(ListCodec.java:46)
[19:17:25 WARN]:        at com.mojang.serialization.JsonOps.lambda$getList$21(JsonOps.java:292)
[19:17:25 WARN]:        at com.mojang.serialization.codecs.ListCodec.lambda$decode$4(ListCodec.java:45)
[19:17:25 WARN]:        at com.mojang.serialization.DataResult.lambda$flatMap$11(DataResult.java:139)
[19:17:25 WARN]:        at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
[19:17:25 WARN]:        at com.mojang.serialization.DataResult.flatMap(DataResult.java:137)
[19:17:25 WARN]:        at com.mojang.serialization.codecs.ListCodec.decode(ListCodec.java:39)
[19:17:25 WARN]:        at com.mojang.serialization.Decoder.parse(Decoder.java:18)
[19:17:25 WARN]:        at com.mojang.serialization.codecs.OptionalFieldCodec.decode(OptionalFieldCodec.java:32)
[19:17:25 WARN]:        at com.mojang.serialization.codecs.RecordCodecBuilder$Instance$7.decode(RecordCodecBuilder.java:408)
[19:17:25 WARN]:        at com.mojang.serialization.codecs.RecordCodecBuilder$2.decode(RecordCodecBuilder.java:107)
[19:17:25 WARN]:        at com.mojang.serialization.MapDecoder.lambda$compressedDecode$1(MapDecoder.java:52)
[19:17:25 WARN]:        at com.mojang.serialization.DataResult.lambda$flatMap$11(DataResult.java:139)
[19:17:25 WARN]:        at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
[19:17:25 WARN]:        at com.mojang.serialization.DataResult.flatMap(DataResult.java:137)
[19:17:25 WARN]:        at com.mojang.serialization.MapDecoder.compressedDecode(MapDecoder.java:52)
[19:17:25 WARN]:        at com.mojang.serialization.MapCodec$MapCodecCodec.decode(MapCodec.java:91)
[19:17:25 WARN]:        at com.mojang.serialization.Decoder.parse(Decoder.java:18)
[19:17:25 WARN]:        at Battlegrounds-1.0.0-SNAPSHOT.jar//org.empirewar.battlegrounds.serialization.gson.game.map.MapAdapter.deserialize(MapAdapter.java:34)
[19:17:25 WARN]:        at Battlegrounds-1.0.0-SNAPSHOT.jar//org.empirewar.battlegrounds.serialization.gson.game.map.MapAdapter.deserialize(MapAdapter.java:21)
[19:17:25 WARN]:        at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:76)
[19:17:25 WARN]:        at com.google.gson.Gson.fromJson(Gson.java:1214)
[19:17:25 WARN]:        at com.google.gson.Gson.fromJson(Gson.java:1124)
[19:17:25 WARN]:        at com.google.gson.Gson.fromJson(Gson.java:1062)
[19:17:25 WARN]:        at Battlegrounds-1.0.0-SNAPSHOT.jar//org.empirewar.battlegrounds.game.GameManager.warmup(GameManager.java:92)
[19:17:25 WARN]:        at Battlegrounds-1.0.0-SNAPSHOT.jar//org.empirewar.battlegrounds.game.GameManager.<init>(GameManager.java:72)
[19:17:25 WARN]:        at Battlegrounds-1.0.0-SNAPSHOT.jar//org.empirewar.battlegrounds.Battlegrounds.enable(Battlegrounds.java:165)
[19:17:25 WARN]:        at Battlegrounds-1.0.0-SNAPSHOT.jar//me.lucko.helper.plugin.ExtendedJavaPlugin.onEnable(ExtendedJavaPlugin.java:89)
[19:17:25 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:279)
[19:17:25 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:192)
[19:17:25 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
[19:17:25 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
[19:17:25 WARN]:        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugin(CraftServer.java:556)
[19:17:25 WARN]:        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugins(CraftServer.java:467)
[19:17:25 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:638)
[19:17:25 WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437)
[19:17:25 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:316)
[19:17:25 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1108)
[19:17:25 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
[19:17:25 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[19:17:25 WARN]: Caused by: java.lang.reflect.InvocationTargetException
[19:17:25 WARN]:        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:119)
[19:17:25 WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:577)
[19:17:25 WARN]:        at com.github.shynixn.structureblocklib.api.bukkit.StructureBlockLib.loadStructure(StructureBlockLib.java:82)
[19:17:25 WARN]:        ... 54 more
[19:17:25 WARN]: Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: com/github/shynixn/structureblocklib/bukkit//TypeConversionServiceImpl
[19:17:25 WARN]:        at com.github.shynixn.structureblocklib.bukkit.Main.createStructureLoader(Main.java:93)
[19:17:25 WARN]:        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[19:17:25 WARN]:        ... 56 more
[19:17:25 WARN]: Caused by: java.lang.ClassNotFoundException: com/github/shynixn/structureblocklib/bukkit//TypeConversionServiceImpl
[19:17:25 WARN]:        at java.base/java.lang.Class.forName0(Native Method)
[19:17:25 WARN]:        at java.base/java.lang.Class.forName(Class.java:383)
[19:17:25 WARN]:        at java.base/java.lang.Class.forName(Class.java:376)
[19:17:25 WARN]:        at com.github.shynixn.structureblocklib.bukkit.Main.findClazz(Main.java:105)
[19:17:25 WARN]:        at com.github.shynixn.structureblocklib.bukkit.Main.createStructureLoader(Main.java:84)
[19:17:25 WARN]:        ... 57 more
```

**Comment by Shynixn** [comment]
1.19.4 is not supported yet. The NMS layer needs to be implemented for it.
I'll try to get to it soon.
