### ISSUE TITLE
I got exception when using your StructureBlockLib

### ISSUE THREAD

**Issue by Sellmak** [Shynixn/StructureBlockLib#17]
Hi,

The exception probably happened because of the fact that I use version 1.13.2-R0.1-SNAPSHOT
You use:
<groupId>org.spigotmc</groupId>
<artifactId>spigot113R2</artifactId>
<version>1.13.2-R2.0</version>

Where Can i found this version of server?(1.13.2-R2.0)

java.lang.ClassNotFoundException: org.bukkit.craftbukkit.v1_13_R2.v1_13_R2.CraftWorld
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_191]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_191]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349) ~[?:1.8.0_191]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_191]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_191]
	at java.lang.Class.forName(Class.java:264) ~[?:1.8.0_191]
	at com.github.shynixn.structureblocklib.bukkit.core.business.service.PersistenceStructureServiceImpl.findClazz(PersistenceStructureServiceImpl.java:257) ~[craftbukkit-1.13.2-R0.1-SNAPSHOT.jar:git-Bukkit-1b982fd]
	at com.github.shynixn.structureblocklib.bukkit.core.business.service.PersistenceStructureServiceImpl.save(PersistenceStructureServiceImpl.java:115) ~[craftbukkit-1.13.2-R0.1-SNAPSHOT.jar:git-Bukkit-1b982fd]
	at com.github.shynixn.structureblocklib.bukkit.core.business.service.PersistenceStructureServiceImpl.save(PersistenceStructureServiceImpl.java:89) ~[craftbukkit-1.13.2-R0.1-SNAPSHOT.jar:git-Bukkit-1b982fd]

**Comment by LazoYoung** [comment]
#15 It seems that 1.13.2 port has not been finished yet.

**Comment by Sellmak** [comment]
LazoYoung what this mean exacly ?

**Comment by LazoYoung** [comment]
> LazoYoung what this mean exacly ?

It means that version is not supported yet in this plugin. Please wait until the fix is done.

**Comment by Sellmak** [comment]
So for what version of the server is the version of this library present?

**Comment by LazoYoung** [comment]
Use 1.13.1 now. Sorry for delayed reply because my timezone may differ from you

**Comment by Shynixn** [comment]
I'll publish the 1.13.2 version, seems like something happend while releasing.

**Comment by Sellmak** [comment]
hi,

The strange thing is that in the name of the class package, there are repeated names of the Minecraft version, such as "1_13_R2.v1_13_R2".
Maybe it misuses your library in the wrong way.

I do it like this:
I add dependency to the pom.xml file of the CraftBukkit server
<Dependency>
      <GroupId> com.github.shynixn.structureblocklib </ groupId>
      <ArtifactId> structureblocklib-bukkit-core </ artifactId>
      <Version> 1.7.0 </ version>
      <Scope> compile </ scope>
</ Dependency>

I add dependency to my plugin:
<Dependency>
<GroupId> com.github.shynixn.structureblocklib </ groupId>
             <ArtifactId> structureblocklib-bukkit-api </ artifactId>
             <Version> 1.7.0 </ version>
             <Scope> provided </ scope>
         </ Dependency>

Is this how your library should be used?

Thank you for your response.
It's great that you'll prepare a plugin for version 1.13.2

**Comment by Shynixn** [comment]
I have just published 1.7.0 so it takes a while to get spread into maven central but thanks for your quick feedback. However, there seems to be a problem with different NMS code in different updates 1.13.2 which I'm investigating right now. I'll probably need to release 1.8.0 version soon.
